"""Object storage abstraction.

Private files (resumes, certificates, offer letters) are never reachable from a public
URL. Both backends issue short-lived signed URLs: S3 uses the provider's own presigning,
the local backend uses an HMAC over ``(object_key, expiry)`` verified by the download
endpoint. The local backend is development-only and refuses to start in production.
"""

from __future__ import annotations

import asyncio
import hashlib
import mimetypes
import re
import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from functools import lru_cache
from pathlib import Path

from app.core.config import settings
from app.core.exceptions import ExternalServiceError, ResourceNotFound
from app.core.logging import get_logger
from app.core.security import sign_storage_path

logger = get_logger(__name__)

#: Object keys are generated by us, never taken from user input, but this is enforced
#: anyway so a future caller cannot introduce path traversal.
_SAFE_KEY_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9/_.\-]{0,510}$")


@dataclass(slots=True)
class StoredObject:
    object_key: str
    size_bytes: int
    content_type: str
    checksum_sha256: str


def build_object_key(
    *, company_id: uuid.UUID | str, category: str, filename: str, entity_id: uuid.UUID | str | None = None
) -> str:
    """Deterministic, collision-free, tenant-prefixed key.

    The company prefix means an accidental cross-tenant read is also a key mismatch, and
    makes per-tenant lifecycle/retention rules expressible directly in the bucket.
    """
    suffix = Path(filename).suffix.lower()[:12]
    suffix = re.sub(r"[^a-z0-9.]", "", suffix)
    stamp = datetime.now(UTC).strftime("%Y/%m")
    unique = uuid.uuid4().hex
    parts = ["companies", str(company_id), category, stamp]
    if entity_id:
        parts.append(str(entity_id))
    parts.append(f"{unique}{suffix}")
    return "/".join(parts)


def validate_object_key(object_key: str) -> None:
    if ".." in object_key or not _SAFE_KEY_RE.match(object_key):
        raise ExternalServiceError("Invalid object key", code="INVALID_OBJECT_KEY")


class StorageProvider(ABC):
    name: str = "abstract"
    is_durable: bool = False

    @abstractmethod
    async def put(self, object_key: str, data: bytes, *, content_type: str | None = None) -> StoredObject: ...

    @abstractmethod
    async def get(self, object_key: str) -> bytes: ...

    @abstractmethod
    async def delete(self, object_key: str) -> None: ...

    @abstractmethod
    async def exists(self, object_key: str) -> bool: ...

    @abstractmethod
    async def signed_url(self, object_key: str, *, expires_in: int | None = None) -> str: ...

    @staticmethod
    def _describe(object_key: str, data: bytes, content_type: str | None) -> StoredObject:
        guessed = content_type or mimetypes.guess_type(object_key)[0] or "application/octet-stream"
        return StoredObject(
            object_key=object_key,
            size_bytes=len(data),
            content_type=guessed,
            checksum_sha256=hashlib.sha256(data).hexdigest(),
        )


class LocalStorageProvider(StorageProvider):
    """Filesystem backend for local development.

    Files land under ``STORAGE_LOCAL_PATH``. Access still requires a valid signature, so
    the development path exercises the same authorisation flow as production rather than
    a permissive shortcut that hides bugs.
    """

    name = "local"
    is_durable = False

    def __init__(self, root: str | None = None) -> None:
        self.root = Path(root or settings.STORAGE_LOCAL_PATH).resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    def _path(self, object_key: str) -> Path:
        validate_object_key(object_key)
        path = (self.root / object_key).resolve()
        # Belt and braces: even with a validated key, confirm we stayed inside the root.
        if not path.is_relative_to(self.root):
            raise ExternalServiceError("Invalid object key", code="INVALID_OBJECT_KEY")
        return path

    async def put(
        self, object_key: str, data: bytes, *, content_type: str | None = None
    ) -> StoredObject:
        path = self._path(object_key)

        def _write() -> None:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)

        await asyncio.to_thread(_write)
        return self._describe(object_key, data, content_type)

    async def get(self, object_key: str) -> bytes:
        path = self._path(object_key)
        if not path.is_file():
            raise ResourceNotFound("File", object_key)
        return await asyncio.to_thread(path.read_bytes)

    async def delete(self, object_key: str) -> None:
        path = self._path(object_key)
        if path.is_file():
            await asyncio.to_thread(path.unlink)

    async def exists(self, object_key: str) -> bool:
        return self._path(object_key).is_file()

    async def signed_url(self, object_key: str, *, expires_in: int | None = None) -> str:
        validate_object_key(object_key)
        ttl = expires_in or settings.STORAGE_SIGNED_URL_TTL_SECONDS
        expires_at = int((datetime.now(UTC) + timedelta(seconds=ttl)).timestamp())
        signature = sign_storage_path(object_key, expires_at)
        return (
            f"{settings.BACKEND_BASE_URL}{settings.API_V1_PREFIX}/files/download"
            f"?key={object_key}&expires={expires_at}&signature={signature}"
        )


class S3StorageProvider(StorageProvider):
    """S3-compatible backend (AWS S3, MinIO, R2, Spaces...).

    ``aioboto3`` is imported lazily so the dependency is only required when S3 storage is
    actually configured.
    """

    name = "s3"
    is_durable = True

    def __init__(self) -> None:
        missing = [
            key
            for key, value in (
                ("STORAGE_BUCKET", settings.STORAGE_BUCKET),
                ("STORAGE_ACCESS_KEY", settings.STORAGE_ACCESS_KEY),
                ("STORAGE_SECRET_KEY", settings.STORAGE_SECRET_KEY),
            )
            if not value
        ]
        if missing:
            from app.core.exceptions import ProviderNotConfigured

            raise ProviderNotConfigured(
                "S3 storage", hint=f"Missing configuration: {', '.join(missing)}"
            )
        self.bucket = settings.STORAGE_BUCKET

    def _session(self):
        import aioboto3

        return aioboto3.Session()

    def _client_kwargs(self) -> dict:
        kwargs = {
            "region_name": settings.STORAGE_REGION,
            "aws_access_key_id": settings.STORAGE_ACCESS_KEY,
            "aws_secret_access_key": settings.STORAGE_SECRET_KEY,
        }
        if settings.STORAGE_ENDPOINT:
            kwargs["endpoint_url"] = settings.STORAGE_ENDPOINT
        return kwargs

    async def put(
        self, object_key: str, data: bytes, *, content_type: str | None = None
    ) -> StoredObject:
        validate_object_key(object_key)
        described = self._describe(object_key, data, content_type)
        extra: dict[str, str] = {}
        # AWS S3 and MinIO honour this header; Cloudflare R2 encrypts every object
        # automatically and rejects the request that asks for it. Sending it is the safer
        # default, so it stays on unless a deployment explicitly opts out.
        if settings.STORAGE_SERVER_SIDE_ENCRYPTION:
            extra["ServerSideEncryption"] = settings.STORAGE_SERVER_SIDE_ENCRYPTION

        async with self._session().client("s3", **self._client_kwargs()) as client:
            await client.put_object(
                Bucket=self.bucket,
                Key=object_key,
                Body=data,
                ContentType=described.content_type,
                Metadata={"sha256": described.checksum_sha256},
                **extra,
            )
        return described

    async def get(self, object_key: str) -> bytes:
        validate_object_key(object_key)
        async with self._session().client("s3", **self._client_kwargs()) as client:
            try:
                response = await client.get_object(Bucket=self.bucket, Key=object_key)
                return await response["Body"].read()
            except client.exceptions.NoSuchKey as exc:
                raise ResourceNotFound("File", object_key) from exc

    async def delete(self, object_key: str) -> None:
        validate_object_key(object_key)
        async with self._session().client("s3", **self._client_kwargs()) as client:
            await client.delete_object(Bucket=self.bucket, Key=object_key)

    async def exists(self, object_key: str) -> bool:
        validate_object_key(object_key)
        async with self._session().client("s3", **self._client_kwargs()) as client:
            try:
                await client.head_object(Bucket=self.bucket, Key=object_key)
                return True
            except Exception:
                return False

    async def signed_url(self, object_key: str, *, expires_in: int | None = None) -> str:
        validate_object_key(object_key)
        async with self._session().client("s3", **self._client_kwargs()) as client:
            return await client.generate_presigned_url(
                "get_object",
                Params={"Bucket": self.bucket, "Key": object_key},
                ExpiresIn=expires_in or settings.STORAGE_SIGNED_URL_TTL_SECONDS,
            )


@lru_cache(maxsize=1)
def get_storage() -> StorageProvider:
    if settings.STORAGE_PROVIDER == "s3":
        logger.info("storage_provider_selected", provider="s3", bucket=settings.STORAGE_BUCKET)
        return S3StorageProvider()
    logger.info("storage_provider_selected", provider="local", path=settings.STORAGE_LOCAL_PATH)
    return LocalStorageProvider()


def reset_storage() -> None:
    get_storage.cache_clear()
